apiVersion: v1
kind: Service
metadata:
  name: web-service-nodeport
  namespace: insightlearn
  labels:
    app: insightlearn-web
spec:
  type: NodePort
  selector:
    app: insightlearn-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-nodeport
  namespace: insightlearn
  labels:
    app: insightlearn-api
spec:
  type: NodePort
  selector:
    app: insightlearn-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31081
    name: http
